server:
  port: 8080

  #컨트롤러가 뷰 이름을 반환할때 thymeleaf/ 로 시작하면 타임리프로 처리하도록 view-names 지정
spring:
  thymeleaf:
    view-names: thymeleaf/*
    prefix: classpath:templates/
    suffix: .html
    #타임리프 브라우저 새로고침 시 자동반영
    cache: false
    check-template-location: true

  #mariaDB 연결
  datasource:
    driverClassName: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://lnkdb.civs5uqopm7i.ap-northeast-2.rds.amazonaws.com:3306/innodb
    username: admin
    password: gksthdls12
  main:
    allow-bean-definition-overriding: true

  #JPA
  #DDL에 변경사항이 있을경우 자동으로 업데이트
  jpa:
    hibernate:
      ddl-auto: update
  #Dialect 설정
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect
  #하이버네이트가 실행하는 SQL문 콘솔 출력
        show_sql: true
  #콘솔에 출력되는 JPA 실행 쿼리를 가독성있게 표현
        format_sql: true
  #디버깅이 용이하도록 SQL문 이외에 추가적인 정보를 출력
        use_sql_comments: true

cloud:
  aws:
    credentials:
      accessKey: AKIAINLGFVU5FME4GQNA
      secretKey: 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
    s3:
      bucket: lnks3
    region:
      static: ap-northeast-2
    stack:
      auto: false
